### ISSUE TITLE
CLI should have a command to create a template project

### ISSUE THREAD

**Issue by Dodecahedr0x** [nautilus-project/nautilus#46]
Current way to get started using Nautilus is to do `cargo init` and copy/paste one of the test sample.

It would be better to have a CLI command to create and configure the project accordingly

**Comment by buffalojoec** [comment]
Love this idea, I think it can live in the CLI directory as a template file - like Jinja or something similar. This would be an amazing idea and we can lay down a `nautilus init` command!
