### ISSUE TITLE
Write more docs!

### ISSUE THREAD

**Issue by buffalojoec** [nautilus-project/nautilus#55]
I am willing to take this on, but if anyone wants to lend a hand, please do!

I've peppered the entire Rust codebase with comments and descriptions of what everything is doing, and very soon I'm going to create a video explaining exactly how the macros work and where to find the key ingredients.

Regardless, as we get closer to beta release, we're gonna need some docs!

Feel free to join me in grabbing anything worth covering in detail from the codebase and documenting it in the markdown files on the doc site: `docs/md`

**Comment by ajwadjaved** [comment]
Hi, I can take this on with you! Would be my first time writing documentation for a project such as this so might need a bit of help at the start.

**Comment by buffalojoec** [comment]
go for it, mate! The code blocks on the docs site look pretty shaky right now, as mentioned in #52 but don't let that stop you

**Comment by ajwadjaved** [comment]
Alright :), will start going through the code and see where I can contribute. If I have any questions is this a good medium to ask them or is there any other specific channel where I could post them?
