### ISSUE TITLE
Make `splogger` part of the core Nautilus crate

### ISSUE THREAD

**Issue by buffalojoec** [nautilus-project/nautilus#56]
Nautilus is built with `splogger` - a [custom Solana program logger library](https://github.com/nautilus-project/splogger) - to give developers cool log formatting for their program logs.

In the `tests`, it's being imported separately from `use nautilus::*;`, but in reality it should probably just be included.

This is a pretty simple change in `lib.rs`

**Comment by cdhiraj40** [comment]
Happy to start contributing to `nautilus` with this :)
@buffalojoec

**Comment by buffalojoec** [comment]
@cdhiraj40 let's get it!
